# Generated by Django 5.2.7 on 2025-12-19 09:59

import django.core.validators
import django.db.models.deletion
import venues.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0002_remove_partnerprofile_contact_person_name_and_more"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "Free WiFi", "Parking", "Air Conditioning"',
                        max_length=100,
                        unique=True,
                        verbose_name="amenity name",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text='Font Awesome class (e.g., "fa-wifi")',
                        max_length=100,
                        verbose_name="icon class",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "Facilities", "Services", "Entertainment"',
                        max_length=50,
                        verbose_name="category",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "venue amenity",
                "verbose_name_plural": "venue amenities",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved & Active"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Temporarily Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the venue",
                        max_length=255,
                        verbose_name="venue name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurant & Dining"),
                            ("BAR_LOUNGE", "Bar & Lounge"),
                            ("NIGHTCLUB", "Nightclub"),
                            ("GYM", "Gym & Fitness Center"),
                            ("SPA", "Spa & Wellness"),
                            ("HOTEL", "Hotel & Resort"),
                            ("BEACH_CLUB", "Beach Club"),
                            ("POOL", "Swimming Pool"),
                            ("CINEMA", "Cinema & Theater"),
                            ("ENTERTAINMENT", "Entertainment Venue"),
                            ("EVENT_SPACE", "Event Space"),
                            ("SPORTS", "Sports Facility"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text='Short catchy description (e.g., "Lagos\' Premier Rooftop Bar")',
                        max_length=200,
                        verbose_name="tagline",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the venue",
                        verbose_name="description",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary contact number",
                        max_length=20,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                ("state", models.CharField(max_length=100, verbose_name="state")),
                (
                    "suburb",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="suburb/area"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="longitude",
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("BUDGET", "₦ Budget-Friendly"),
                            ("MODERATE", "₦₦ Moderate"),
                            ("UPSCALE", "₦₦₦ Upscale"),
                            ("LUXURY", "₦₦₦₦ Luxury"),
                        ],
                        default="MODERATE",
                        max_length=20,
                        verbose_name="price range",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of guests",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="capacity",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        help_text="Main venue image (will be optimized to WebP)",
                        upload_to=venues.models.VenueUploadPath("cover"),
                        validators=[venues.models.validate_image_size],
                        verbose_name="cover image",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="opening time"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="closing time"
                    ),
                ),
                (
                    "open_24_hours",
                    models.BooleanField(default=False, verbose_name="open 24 hours"),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="For search engines (max 160 chars)",
                        max_length=160,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="view count"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="average rating",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="total reviews"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_venues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="account.partnerprofile",
                        verbose_name="partner owner",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="venues",
                        to="venues.venueamenity",
                        verbose_name="amenities",
                    ),
                ),
            ],
            options={
                "verbose_name": "venue",
                "verbose_name_plural": "venues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("visit_date", models.DateField()),
                (
                    "guests_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("CHECKED_IN", "Checked In"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CONFIRMED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "SUBSCRIBER"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="venues.venue"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_venues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "venue favorite",
                "verbose_name_plural": "venue favorites",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=venues.models.VenueUploadPath("gallery"),
                        validators=[venues.models.validate_image_size],
                        verbose_name="image",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="caption"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="For accessibility",
                        max_length=255,
                        verbose_name="alt text",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="display order"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show in main gallery highlights",
                        verbose_name="featured",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "venue image",
                "verbose_name_plural": "venue images",
                "ordering": ["display_order", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="review title"
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        help_text="Share your experience", verbose_name="review"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="approved"),
                ),
                (
                    "is_verified_visit",
                    models.BooleanField(
                        default=False,
                        help_text="User has booking/visit record",
                        verbose_name="verified visit",
                    ),
                ),
                (
                    "helpful_count",
                    models.IntegerField(default=0, verbose_name="helpful votes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "SUBSCRIBER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "venue review",
                "verbose_name_plural": "venue reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["slug"], name="venues_venu_slug_f5c9e1_idx"),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["status", "category"], name="venues_venu_status_49e8c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["city", "state"], name="venues_venu_city_e9a0b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["-average_rating"], name="venues_venu_average_0d98ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venuebooking",
            index=models.Index(
                fields=["user", "status"], name="venues_venu_user_id_28b049_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venuebooking",
            index=models.Index(
                fields=["venue", "visit_date"], name="venues_venu_venue_i_9ab0ba_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="venuefavorite",
            unique_together={("user", "venue")},
        ),
        migrations.AddIndex(
            model_name="venuereview",
            index=models.Index(
                fields=["venue", "is_approved"], name="venues_venu_venue_i_99998e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venuereview",
            index=models.Index(
                fields=["-created_at"], name="venues_venu_created_1d1a05_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="venuereview",
            unique_together={("venue", "user")},
        ),
    ]
