# Generated by Django 5.2.7 on 2025-12-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="price_range",
        ),
        migrations.AlterField(
            model_name="venue",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Business address"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the business",
                verbose_name="business description",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Business email"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(
                help_text="Official name of the business",
                max_length=255,
                verbose_name="business name",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="phone",
            field=models.CharField(
                help_text="Primary contact number",
                max_length=20,
                verbose_name="Business phone number",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="website",
            field=models.URLField(blank=True, verbose_name="Business website"),
        ),
    ]
