# Generated by Django 5.2.7 on 2026-02-19 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_partnerprofile_account_name_and_more"),
        ("subscriptions", "0003_remove_planfeatureassignment_custom_value_and_more"),
        ("venues", "0002_remove_venue_price_range_alter_venue_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="primary_feature",
            field=models.ForeignKey(
                blank=True,
                help_text="Which subscription feature does visiting this venue consume? (e.g., Gym Access, Buffet)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="venues",
                to="subscriptions.planfeature",
                verbose_name="primary feature",
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["latitude", "longitude"], name="venues_venu_latitud_1267ec_idx"
            ),
        ),
    ]
