# Generated by Django 5.2.7 on 2026-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0003_venue_primary_feature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("SUBSCRIPTION", "Subscription Only"),
                    ("STORE", "Discount Store Only"),
                    ("BOTH", "Both (Subscription & Store)"),
                ],
                default="BOTH",
                help_text="SUBSCRIPTION = only appears in subscriber venue list. STORE = only appears in Discount Store. BOTH = appears in both places.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="star_tier",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Level 1 — All Members"),
                    (2, "Level 2 — Mid-tier & Above"),
                    (3, "Level 3 — Top-tier Only"),
                ],
                default=1,
                help_text="Minimum subscription level required to access this venue.",
            ),
        ),
    ]
