# Generated by Django 5.2.7 on 2026-04-09 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0004_venue_access_mode_venue_star_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="store_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Price for this venue in the Discount Store (in naira). 1 naira = 1 coin. Only used when access_mode is STORE or BOTH.",
                max_digits=10,
            ),
        ),
    ]
