# Generated by Django 5.2.7 on 2025-12-12 15:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("SUBSCRIBER", "Subscriber"),
                            ("PARTNER", "Partner"),
                            ("ADMIN", "Admin"),
                        ],
                        default="SUBSCRIBER",
                        max_length=10,
                        verbose_name="user type",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="PartnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=255, verbose_name="business name"),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurant"),
                            ("GYM", "Gym/Fitness Center"),
                            ("SPA", "Spa/Wellness"),
                            ("HOTEL", "Hotel/Resort"),
                            ("BEACH_CLUB", "Beach Club"),
                            ("POOL", "Swimming Pool"),
                            ("ENTERTAINMENT", "Entertainment Venue"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="business type",
                    ),
                ),
                (
                    "contact_person_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Name of person to contact",
                        max_length=255,
                        verbose_name="contact person name",
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Corporate Affairs Commission (CAC) number",
                        max_length=50,
                        verbose_name="CAC registration number",
                    ),
                ),
                (
                    "tax_identification_number",
                    models.CharField(blank=True, max_length=50, verbose_name="TIN"),
                ),
                (
                    "business_phone",
                    models.CharField(max_length=20, verbose_name="business phone"),
                ),
                (
                    "business_email",
                    models.EmailField(max_length=254, verbose_name="business email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "business_address",
                    models.CharField(max_length=255, verbose_name="business address"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                ("state", models.CharField(max_length=100, verbose_name="state")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="business description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/logos/"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="bank name"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="account number"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="account name"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
                (
                    "business_license",
                    models.FileField(
                        blank=True,
                        help_text="Upload business license/CAC certificate",
                        null=True,
                        upload_to="partners/documents/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_partners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "PARTNER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "partner profile",
                "verbose_name_plural": "partner profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=10,
                        verbose_name="gender",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/subscribers/"
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="state"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Nigeria", max_length=100, verbose_name="country"
                    ),
                ),
                ("receive_notifications", models.BooleanField(default=True)),
                ("receive_marketing_emails", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "SUBSCRIBER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscriber profile",
                "verbose_name_plural": "subscriber profiles",
            },
        ),
    ]
