# Generated by Django 5.2.7 on 2025-12-19 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnerprofile",
            name="contact_person_name",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="website",
        ),
    ]
