# Generated by Django 5.2.7 on 2025-12-23 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_partnerprofile_contact_person_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnerprofile",
            name="business_address",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="business_email",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="business_phone",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="business_registration_number",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="business_type",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="tax_identification_number",
        ),
    ]
