# Generated by Django 5.2.7 on 2026-01-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_remove_partnerprofile_business_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerprofile",
            name="account_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="account name",
            ),
        ),
        migrations.AlterField(
            model_name="partnerprofile",
            name="account_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                null=True,
                verbose_name="account number",
            ),
        ),
        migrations.AlterField(
            model_name="partnerprofile",
            name="bank_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="bank name",
            ),
        ),
    ]
