# Generated by Django 5.2.7 on 2026-02-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_partnerprofile_account_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(
                choices=[("NG", "Nigeria")],
                default="NG",
                help_text="Select the country where you are located",
                max_length=100,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=models.CharField(
                choices=[
                    ("AB", "Abia"),
                    ("AD", "Adamawa"),
                    ("AK", "Akwa Ibom"),
                    ("AN", "Anambra"),
                    ("BA", "Bauchi"),
                    ("BY", "Bayelsa"),
                    ("BE", "Benue"),
                    ("BO", "Borno"),
                    ("CR", "Cross River"),
                    ("DE", "Delta"),
                    ("EB", "Ebonyi"),
                    ("ED", "Edo"),
                    ("EK", "Ekiti"),
                    ("EN", "Enugu"),
                    ("FC", "FCT (Abuja)"),
                    ("GO", "Gombe"),
                    ("IM", "Imo"),
                    ("JI", "Jigawa"),
                    ("KD", "Kaduna"),
                    ("KN", "Kano"),
                    ("KT", "Katsina"),
                    ("KE", "Kebbi"),
                    ("KO", "Kogi"),
                    ("KW", "Kwara"),
                    ("LA", "Lagos"),
                    ("NA", "Nasarawa"),
                    ("NI", "Niger"),
                    ("OG", "Ogun"),
                    ("ON", "Ondo"),
                    ("OS", "Osun"),
                    ("OY", "Oyo"),
                    ("PL", "Plateau"),
                    ("RI", "Rivers"),
                    ("SO", "Sokoto"),
                    ("TA", "Taraba"),
                    ("YO", "Yobe"),
                    ("ZA", "Zamfara"),
                ],
                default="LA",
                help_text="Select the state where you are located",
                max_length=2,
                verbose_name="state",
            ),
        ),
    ]
