# Generated by Django 5.2.7 on 2026-03-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_userprofile_country_alter_userprofile_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gp_id",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Unique Gold Privilege identifier, e.g. GP-A3X9K2. Auto-generated on creation.",
                max_length=10,
                verbose_name="GP ID",
            ),
        ),
    ]
