# Generated by Django 5.2.7 on 2026-03-11 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subscriptions", "0004_remove_subscriptionplan_max_bookings_per_month"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AIRTIME", "Mobile Airtime"),
                            ("DATA", "Internet Data"),
                            ("RIDE_VOUCHER", "Ride Voucher"),
                            ("FUEL_VOUCHER", "Fuel Voucher"),
                            ("OTHER", "Other Service"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("API_INSTANT", "API – Instant Delivery (VTPass)"),
                            ("MANUAL_CODE", "Manual – Voucher Code"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome class e.g. fa-mobile-alt",
                        max_length=100,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum naira amount (for airtime/data)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum naira amount (for airtime/data)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fixed_amounts",
                    models.JSONField(
                        blank=True,
                        help_text="Fixed naira denominations e.g. [5000, 10000, 20000]",
                        null=True,
                    ),
                ),
                (
                    "has_inventory",
                    models.BooleanField(
                        default=False,
                        help_text="Tick for Uber/Bolt/Petrol vouchers that need stored codes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VoucherInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_code", models.CharField(max_length=200, unique=True)),
                (
                    "voucher_pin",
                    models.CharField(
                        blank=True,
                        help_text="Optional PIN if required for redemption",
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What you paid for this voucher",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned to User"),
                            ("USED", "Confirmed Used"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "voucher inventory",
                "verbose_name_plural": "voucher inventory",
            },
        ),
        migrations.CreateModel(
            name="ServicePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                (
                    "network_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn", "MTN"),
                            ("glo", "Glo"),
                            ("airtel", "Airtel"),
                            ("etisalat", "9mobile"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("api_response", models.JSONField(blank=True, null=True)),
                ("api_transaction_id", models.CharField(blank=True, max_length=200)),
                ("used_quota", models.BooleanField(default=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="services.service",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_purchases",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase",
                        to="services.voucherinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "service purchase",
                "verbose_name_plural": "service purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServicePlanQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uses_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Max uses per month. Leave blank for unlimited.",
                        null=True,
                    ),
                ),
                (
                    "max_value_per_use",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Max naira value per single use (for airtime/data). Leave blank for no cap.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_quotas",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_quotas",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "service plan quota",
                "verbose_name_plural": "service plan quotas",
                "unique_together": {("plan", "service")},
            },
        ),
        migrations.CreateModel(
            name="ServiceQuotaUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_year", models.PositiveIntegerField()),
                ("period_month", models.PositiveIntegerField()),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota_usages",
                        to="services.service",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_quota_usages",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_quota_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "service quota usage",
                "verbose_name_plural": "service quota usages",
                "indexes": [
                    models.Index(
                        fields=["user", "period_year", "period_month"],
                        name="services_se_user_id_2f0dfc_idx",
                    )
                ],
                "unique_together": {("user", "service", "period_year", "period_month")},
            },
        ),
        migrations.AddIndex(
            model_name="voucherinventory",
            index=models.Index(
                fields=["service", "status"], name="services_vo_service_21dc61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicepurchase",
            index=models.Index(
                fields=["user", "status"], name="services_se_user_id_cbb0fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicepurchase",
            index=models.Index(
                fields=["created_at"], name="services_se_created_91c599_idx"
            ),
        ),
    ]
