# Generated by Django 5.2.7 on 2026-03-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicequotausage",
            old_name="used_count",
            new_name="count_used",
        ),
        migrations.RemoveField(
            model_name="service",
            name="max_amount",
        ),
        migrations.RemoveField(
            model_name="service",
            name="min_amount",
        ),
        migrations.RemoveField(
            model_name="serviceplanquota",
            name="max_value_per_use",
        ),
        migrations.RemoveField(
            model_name="serviceplanquota",
            name="uses_limit",
        ),
        migrations.AddField(
            model_name="service",
            name="max_transaction_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum naira per single transaction (e.g. 5000). Leave blank — system will use the plan monthly allowance as the ceiling.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="min_transaction_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                help_text="Minimum naira per single transaction (e.g. 100)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceplanquota",
            name="monthly_allowance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total naira allowance per month for this service. Leave blank for unlimited.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceplanquota",
            name="monthly_voucher_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of voucher codes allowed per month. Leave blank for unlimited. Only applies to voucher services.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicequotausage",
            name="amount_used",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="service",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("API_INSTANT", "API – Instant Delivery (Reloadly)"),
                    ("MANUAL_CODE", "Manual – Voucher Code"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voucherinventory",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="voucherinventory",
            name="voucher_pin",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
