# Generated by Django 5.2.7 on 2026-03-12 13:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_rename_used_count_servicequotausage_count_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="max_data_gb",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="DATA: Maximum GB per single bundle purchase. Leave blank to use plan allowance.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="min_data_gb",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("0.5"),
                help_text="DATA: Minimum GB per single data bundle (e.g. 0.5 for 500MB)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceplanquota",
            name="monthly_data_gb",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="DATA: Total GB per month (e.g. 5.0 for 5GB). Blank = unlimited.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicepurchase",
            name="data_gb",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="For data purchases: GB purchased",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicepurchase",
            name="variation_code",
            field=models.CharField(
                blank=True,
                help_text="Reloadly variation code for data bundles",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="servicequotausage",
            name="data_gb_used",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="fixed_amounts",
            field=models.JSONField(
                blank=True,
                help_text="VOUCHER: Fixed naira denominations e.g. [5000, 10000, 20000]",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="max_transaction_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="AIRTIME: Maximum naira per top-up (e.g. 5000). Leave blank to use plan allowance.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="min_transaction_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                help_text="AIRTIME: Minimum naira per top-up (e.g. 100)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="serviceplanquota",
            name="monthly_allowance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="AIRTIME: Total naira per month (e.g. 10000). Blank = unlimited.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="serviceplanquota",
            name="monthly_voucher_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="VOUCHER: Number of voucher codes per month. Blank = unlimited.",
                null=True,
            ),
        ),
    ]
