# Generated by Django 5.2.7 on 2026-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_service_max_data_gb_service_min_data_gb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherinventory",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Only used when voucher_type is PERCENTAGE_DISCOUNT. e.g. 20.00 = 20% off.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="voucherinventory",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Fixed Amount (₦)"),
                    ("PERCENT", "Percentage Discount (%)"),
                ],
                default="FIXED",
                help_text="Fixed: deducts exact naira amount. Percent: deducts a % off.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("AIRTIME", "Mobile Airtime"),
                    ("DATA", "Internet Data"),
                    ("RIDE_VOUCHER", "Ride Voucher"),
                    ("FUEL_VOUCHER", "Fuel Voucher"),
                    ("HOTEL_VOUCHER", "Hotel Voucher"),
                    ("OTHER", "Other Service"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voucherinventory",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="leave at 0 for percentage-based vouchers",
                max_digits=10,
            ),
        ),
    ]
