# Generated by Django 5.2.7 on 2026-03-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_voucherinventory_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceplanquota",
            name="voucher_discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="VOUCHER + PERCENT only: Discount percentage. e.g. 15.00 = 15% off.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceplanquota",
            name="voucher_fixed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="VOUCHER + FIXED only: Face value in naira. e.g. 20000 = ₦20,000 voucher.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceplanquota",
            name="voucher_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIXED", "Fixed Amount (₦)"),
                    ("PERCENT", "Percentage Discount (%)"),
                ],
                help_text="VOUCHER: Which type of voucher this plan provides. FIXED = naira value, PERCENT = percentage discount.",
                max_length=10,
                null=True,
            ),
        ),
    ]
