# Generated by Django 5.2.7 on 2026-05-02 12:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_booking_booking_source_alter_booking_subscription"),
        ("venues", "0005_venue_store_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apply_commission_to_store",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, GP keeps the configured percentage from Discount Store sales before paying the venue.",
                    ),
                ),
                (
                    "store_commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Commission GP keeps from Discount Store sales.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "apply_commission_to_subscription",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, GP also keeps a percentage from subscription venue payouts. Leave off if GP margin is already baked into subscription pricing.",
                    ),
                ),
                (
                    "subscription_commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Commission GP keeps from subscription check-ins.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "payout_delay_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Hours after check-in before a sales record becomes payout-eligible. Examples: 1, 12, 24.",
                    ),
                ),
                (
                    "minimum_payout_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="Minimum net amount required before an automatic payout batch is created.",
                        max_digits=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payout Configuration",
                "verbose_name_plural": "Payout Configuration",
            },
        ),
        migrations.CreateModel(
            name="PayoutRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "total_gross",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_commission",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_net",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("booking_count", models.PositiveIntegerField(default=0)),
                ("store_count", models.PositiveIntegerField(default=0)),
                ("subscription_count", models.PositiveIntegerField(default=0)),
                ("bank_name_snapshot", models.CharField(blank=True, max_length=100)),
                (
                    "account_number_snapshot",
                    models.CharField(blank=True, max_length=20),
                ),
                ("account_name_snapshot", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("transfer_reference", models.CharField(blank=True, max_length=150)),
                ("transfer_notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_venue_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_venue_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_records",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_source",
                    models.CharField(
                        choices=[
                            ("SUBSCRIPTION", "Subscription Visit"),
                            ("STORE", "Discount Store Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the customer-facing source reference.",
                        max_length=40,
                    ),
                ),
                ("checked_in_at", models.DateTimeField()),
                ("eligible_for_payout_at", models.DateTimeField(db_index=True)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_rate_snapshot",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("commission_enabled_snapshot", models.BooleanField(default=False)),
                (
                    "payment_method_snapshot",
                    models.CharField(blank=True, max_length=20),
                ),
                ("guests_count", models.PositiveIntegerField(default=1)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_record",
                        to="bookings.booking",
                    ),
                ),
                (
                    "payout_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_records",
                        to="superadmin.payoutrecord",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_records",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_in_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payoutrecord",
            index=models.Index(
                fields=["venue", "status"], name="superadmin__venue_i_ab5fb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutrecord",
            index=models.Index(
                fields=["status", "created_at"], name="superadmin__status_db49b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(
                fields=["venue", "payout_record"], name="superadmin__venue_i_622b7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(
                fields=["venue", "eligible_for_payout_at"],
                name="superadmin__venue_i_b3602a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(
                fields=["booking_source", "eligible_for_payout_at"],
                name="superadmin__booking_77dc78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(
                fields=["booking_source"], name="superadmin__booking_0bce9b_idx"
            ),
        ),
    ]
