# Generated by Django 5.2.7 on 2026-03-16 10:39

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("venues", "0003_venue_primary_feature_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. Starter Pack", max_length=100),
                ),
                (
                    "coins",
                    models.PositiveIntegerField(
                        help_text="Base coins the user receives"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in Naira (₦)", max_digits=10
                    ),
                ),
                (
                    "bonus_coins",
                    models.PositiveIntegerField(
                        default=0, help_text="Bonus coins on top of base amount"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text='Show "Best Value" badge'
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="WalletConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_transfer_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50000"),
                        help_text="Maximum coins a user can transfer OUT per day",
                        max_digits=12,
                    ),
                ),
                (
                    "referral_coins_reward",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Coins awarded to referrer when referred user completes first subscription payment",
                    ),
                ),
                (
                    "monthly_bonus_tier_1",
                    models.PositiveIntegerField(
                        default=100, help_text="Monthly bonus for Tier 1 plan holders"
                    ),
                ),
                (
                    "monthly_bonus_tier_2",
                    models.PositiveIntegerField(
                        default=250, help_text="Monthly bonus for Tier 2 plan holders"
                    ),
                ),
                (
                    "monthly_bonus_tier_3",
                    models.PositiveIntegerField(
                        default=500, help_text="Monthly bonus for Tier 3 plan holders"
                    ),
                ),
                (
                    "min_transfer_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        help_text="Minimum coins per single transfer",
                        max_digits=10,
                    ),
                ),
                (
                    "max_failed_pin_attempts",
                    models.PositiveIntegerField(
                        default=5, help_text="Failed PIN attempts before 30-min lockout"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wallet Configuration",
                "verbose_name_plural": "Wallet Configuration",
            },
        ),
        migrations.CreateModel(
            name="CashbackRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global (All Purchases)"),
                            ("VENUE", "Specific Venue"),
                        ],
                        default="GLOBAL",
                        max_length=20,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="e.g. 5.00 for 5%",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "minimum_spend",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum order amount to qualify (leave blank = no minimum)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="venues.venue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoinPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins_to_credit", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paystack_reference", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Payment"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wallet.coinpackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "wallet_pin",
                    models.CharField(
                        blank=True,
                        help_text="Hashed wallet PIN — never stored in plain text",
                        max_length=128,
                    ),
                ),
                ("pin_set", models.BooleanField(default=False)),
                ("pin_failed_attempts", models.PositiveIntegerField(default=0)),
                (
                    "pin_locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="PIN entry locked until this time after too many failed attempts",
                        null=True,
                    ),
                ),
                (
                    "daily_transfer_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("daily_transfer_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins_awarded", models.PositiveIntegerField(default=0)),
                ("awarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False,
                        help_text="True once referral bonus coins are credited to referrer",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("referrer", "referred_user")},
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Coin Purchase (Real Money)"),
                            ("SPEND", "Spent in Discount Store"),
                            ("CASHBACK", "Cashback Earned"),
                            ("REFERRAL", "Referral Bonus"),
                            ("TRANSFER_IN", "Received from User"),
                            ("TRANSFER_OUT", "Sent to User"),
                            ("MONTHLY_BONUS", "Monthly Subscription Bonus"),
                            ("REFUND", "Refund (Cancellation)"),
                            ("ADMIN_CREDIT", "Admin Manual Credit"),
                            ("ADMIN_DEBIT", "Admin Manual Debit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Always the absolute amount — direction is encoded in type",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paystack_reference", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="For transfers: the other party",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "type", "created_at"],
                        name="wallet_wall_wallet__3f9695_idx",
                    )
                ],
            },
        ),
    ]
