# Generated by Django 5.2.7 on 2026-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_alter_wallettransaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Coin Purchase (Real Money)"),
                    ("SPEND", "Spent in Discount Store"),
                    ("CASHBACK", "Cashback Earned"),
                    ("CASHBACK_CLAWBACK", "Cashback Removed (Cancellation)"),
                    ("REFERRAL", "Referral Bonus"),
                    ("TRANSFER_IN", "Received from User"),
                    ("TRANSFER_OUT", "Sent to User"),
                    ("MONTHLY_BONUS", "Monthly Subscription Bonus"),
                    ("REFUND", "Refund (Cancellation)"),
                    ("ADMIN_CREDIT", "Admin Manual Credit"),
                    ("ADMIN_DEBIT", "Admin Manual Debit"),
                    ("STORE_PURCHASE", "Discount Store Purchase"),
                    ("STORE_REFUND", "Discount Store Refund"),
                ],
                max_length=20,
            ),
        ),
    ]
