# Generated by Django 5.2.7 on 2025-12-17 10:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "Access to Premium Gyms"',
                        max_length=200,
                        verbose_name="feature name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of this feature",
                        verbose_name="description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Font Awesome icon class (e.g., "fa-dumbbell")',
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which feature appears (lower = first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "plan feature",
                "verbose_name_plural": "plan features",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text='Coupon code (e.g., "LAUNCH2025")',
                        max_length=50,
                        unique=True,
                        verbose_name="promo code",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="description"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED_AMOUNT", "Fixed Amount"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or Fixed Amount in Naira",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="discount value",
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of times this code can be used (empty = unlimited)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="max uses",
                    ),
                ),
                (
                    "uses_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this code has been used",
                        verbose_name="uses count",
                    ),
                ),
                (
                    "max_uses_per_user",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="max uses per user",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="valid from"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="valid until"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "promo code",
                "verbose_name_plural": "promo codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeatureAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_value",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "10 per month" or "Unlimited"',
                        max_length=100,
                        verbose_name="custom value",
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False, help_text="Highlight this feature for this plan"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_assignments",
                        to="subscriptions.planfeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan feature assignment",
                "verbose_name_plural": "plan feature assignments",
                "ordering": ["display_order", "feature__display_order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Internal unique identifier (secure)",
                        unique=True,
                    ),
                ),
                (
                    "subscription_reference",
                    models.CharField(
                        editable=False,
                        help_text="Customer-facing reference (e.g., GP-SUB-A7X9)",
                        max_length=20,
                        unique=True,
                        verbose_name="subscription reference",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="start date")),
                ("end_date", models.DateTimeField(verbose_name="end date")),
                ("is_trial", models.BooleanField(default=False)),
                ("trial_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically renew subscription on expiry",
                        verbose_name="auto renew",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRIAL", "Trial Period"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("PENDING", "Pending Payment"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "price_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price paid",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "bookings_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of bookings made in current period",
                        verbose_name="bookings count",
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "promo_code_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usages",
                        to="subscriptions.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "SUBSCRIBER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Internal unique identifier (secure, never exposed)",
                        unique=True,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        editable=False,
                        help_text="Customer-facing payment reference (e.g., GP-TW7268)",
                        max_length=20,
                        unique=True,
                        verbose_name="payment reference",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("USSD", "USSD"),
                            ("MOBILE_MONEY", "Mobile Money"),
                        ],
                        default="CARD",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference from payment gateway (e.g., Paystack)",
                        max_length=255,
                        verbose_name="gateway reference",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        help_text="Full response from payment gateway",
                        null=True,
                        verbose_name="gateway response",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "Gold", "Platinum", "Diamond"',
                        max_length=100,
                        verbose_name="plan name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name (auto-generated from name)",
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Short description of the plan",
                        verbose_name="description",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text='Catchy tagline (e.g., "Most Popular")',
                        max_length=200,
                        verbose_name="tagline",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in Naira (NGN)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly (3 months)"),
                            ("SEMI_ANNUAL", "Semi-Annual (6 months)"),
                            ("ANNUAL", "Annual (12 months)"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="billing period",
                    ),
                ),
                (
                    "trial_period_days",
                    models.IntegerField(
                        default=0,
                        help_text="Number of free trial days (0 for no trial)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="trial period (days)",
                    ),
                ),
                (
                    "max_bookings_per_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Leave empty for unlimited bookings",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="max bookings per month",
                    ),
                ),
                (
                    "max_guests_per_booking",
                    models.IntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="max guests per booking",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text='Highlight this plan (e.g., "Most Popular")',
                        verbose_name="featured plan",
                    ),
                ),
                (
                    "highlight_color",
                    models.CharField(
                        default="#d4af37",
                        help_text="Hex color code for plan badge/border",
                        max_length=7,
                        verbose_name="highlight color",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which plan appears (lower = first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this plan available for purchase?",
                        verbose_name="active",
                    ),
                ),
                (
                    "available_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Plan becomes available on this date",
                        null=True,
                        verbose_name="available from",
                    ),
                ),
                (
                    "available_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Plan stops being available on this date",
                        null=True,
                        verbose_name="available until",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True,
                        related_name="plans",
                        through="subscriptions.PlanFeatureAssignment",
                        to="subscriptions.planfeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription plan",
                "verbose_name_plural": "subscription plans",
                "ordering": ["display_order", "price"],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="applicable_plans",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all plans",
                related_name="promo_codes",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="planfeatureassignment",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_assignments",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "status"], name="subscriptio_user_id_2a19e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["end_date"], name="subscriptio_end_dat_60694b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planfeatureassignment",
            unique_together={("plan", "feature")},
        ),
    ]
