# Generated by Django 5.2.7 on 2026-02-19 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfeatureassignment",
            name="usage_limit",
            field=models.IntegerField(
                default=1,
                help_text="Number of times this feature can be used per billing period (e.g., 5 gym sessions)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="usage limit",
            ),
        ),
    ]
