# Generated by Django 5.2.7 on 2026-02-19 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_planfeatureassignment_usage_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planfeatureassignment",
            name="custom_value",
        ),
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="times used",
                    ),
                ),
                ("period_year", models.IntegerField(verbose_name="period year")),
                ("period_month", models.IntegerField(verbose_name="period month")),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last used at"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="subscriptions.planfeature",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usages",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "feature usage",
                "verbose_name_plural": "feature usages",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "period_year", "period_month"],
                        name="subscriptio_subscri_fe0951_idx",
                    )
                ],
                "unique_together": {
                    ("subscription", "feature", "period_year", "period_month")
                },
            },
        ),
    ]
