# Generated by Django 5.2.7 on 2026-02-20 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_remove_planfeatureassignment_custom_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="max_bookings_per_month",
        ),
    ]
