# Generated by Django 5.2.7 on 2026-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_remove_subscriptionplan_max_bookings_per_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="venue_tier_access",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Level 1 — Standard venues"),
                    (2, "Level 2 — Level 1 + Premium venues"),
                    (3, "Level 3 — All venues"),
                ],
                default=1,
                help_text="Which venue star tiers this plan unlocks. Level 2 also includes Level 1.",
            ),
        ),
    ]
