# Generated by Django 5.2.7 on 2026-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0006_remove_subscription_venue_tier_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_coming_soon",
            field=models.BooleanField(
                default=False,
                help_text="Mark this plan as Coming Soon — visible but not subscribable",
                verbose_name="coming soon",
            ),
        ),
    ]
