# Generated by Django 5.2.7 on 2026-06-15 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpinPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Text shown on this wheel segment. e.g. "Try Again", "50 Coins", "JACKPOT"',
                        max_length=60,
                    ),
                ),
                (
                    "coins_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = no win (loss). Any positive number = coins credited to wallet on win.",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        help_text="Probability weight as a whole number. All active prizes must sum to exactly 100. Higher = more likely. e.g. 55 means 55% chance."
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#E5AD04",
                        help_text="Hex colour for this wheel segment. Use gold shades: #E5AD04, #F9B036, #5c3001, #020202",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#000000",
                        help_text="Hex colour for the label text on this segment.",
                        max_length=7,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Clockwise position on the wheel, starting from 0. Cosmetic only — does not affect odds.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive prizes are excluded from both the wheel and prize selection.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spin Prize",
                "verbose_name_plural": "Spin Prizes",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SpinConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Turn the spin wheel on or off for all users instantly.",
                    ),
                ),
                (
                    "daily_spin_limit",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="How many spins each subscriber gets per day. Resets at midnight Lagos time (WAT, UTC+1).",
                    ),
                ),
                (
                    "cooldown_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minimum minutes a user must wait between spins. Set to 0 to allow back-to-back spins up to the daily limit.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last admin who saved this config.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Spin Configuration",
                "verbose_name_plural": "Spin Configuration",
            },
        ),
        migrations.CreateModel(
            name="SpinRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coins_awarded",
                    models.PositiveIntegerField(
                        help_text="Snapshot of coins actually credited. 0 for a loss."
                    ),
                ),
                (
                    "spun_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="UTC datetime of the spin.",
                    ),
                ),
                (
                    "lagos_date",
                    models.DateField(
                        help_text="Lagos calendar date of the spin — used for daily limit queries."
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the request for fraud detection.",
                        null=True,
                    ),
                ),
                (
                    "prize",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spin_records",
                        to="games.spinprize",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spin_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Spin Record",
                "verbose_name_plural": "Spin Records",
                "ordering": ["-spun_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "lagos_date"],
                        name="games_spinr_user_id_81b1d3_idx",
                    ),
                    models.Index(
                        fields=["-spun_at"], name="games_spinr_spun_at_5ac154_idx"
                    ),
                ],
            },
        ),
    ]
