# Generated by Django 5.2.7 on 2026-04-02 11:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_booking_booking_source_alter_booking_subscription"),
        ("venues", "0004_venue_access_mode_venue_star_tier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cashback_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Cashback as % of amount paid. e.g. 5.00 = 5 coins per ₦100 spent.",
                        max_digits=5,
                    ),
                ),
                (
                    "cancellation_cutoff_hours",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Users cannot cancel a booking within this many hours of their visit time.",
                    ),
                ),
                (
                    "max_quantity_per_order",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of people/tickets per single order.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store Configuration",
                "verbose_name_plural": "Store Configuration",
            },
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per person in naira. 1 naira = 1 coin.",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="store_products/"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_products",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "store product",
                "verbose_name_plural": "store products",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StoreOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated. Format: GP-DS-XXXXXX",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of people / tickets. Price × quantity = amount_paid.",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CARD", "Credit/Debit Card (Paystack)"),
                            ("COINS", "Gold Coins (Wallet)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "paystack_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Set for CARD payments. Format: GP-DS-XXXXXX (same as reference).",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Payment"),
                            ("PAID", "Paid — Booking Active"),
                            ("USED", "Used / Attended"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "cashback_coins",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Coins to award when payment is confirmed. Calculated at checkout.",
                    ),
                ),
                ("cashback_awarded", models.BooleanField(default=False)),
                (
                    "visit_date",
                    models.DateField(help_text="Date the user will visit the venue."),
                ),
                ("visit_time", models.TimeField(help_text="Preferred visit time.")),
                ("special_notes", models.TextField(blank=True)),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USER", "User"),
                            ("VENUE", "Venue"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_order",
                        to="bookings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="PROTECT prevents deleting a product that has orders.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="discount_store.storeproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "store order",
                "verbose_name_plural": "store orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="discount_st_user_id_2f161c_idx"
                    ),
                    models.Index(
                        fields=["paystack_reference"],
                        name="discount_st_paystac_304e70_idx",
                    ),
                ],
            },
        ),
    ]
