# Generated by Django 5.2.7 on 2026-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeorder",
            name="visit_time",
            field=models.TimeField(
                blank=True, help_text="Preferred visit time.", null=True
            ),
        ),
    ]
