# Generated by Django 5.2.7 on 2025-12-29 12:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        ("venues", "0002_remove_venue_price_range_alter_venue_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Internal unique identifier (never exposed to users)",
                        unique=True,
                        verbose_name="booking UUID",
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(
                        editable=False,
                        help_text="Human-readable reference (e.g., GP-BKABCD12)",
                        max_length=20,
                        unique=True,
                        verbose_name="booking reference",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        help_text="Date member plans to visit",
                        verbose_name="visit date",
                    ),
                ),
                (
                    "guests_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Total guests including member (1-20)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="number of guests",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes for venue (e.g., dietary restrictions, occasion)",
                        verbose_name="special requests",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("CHECKED_IN", "Checked In"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="CONFIRMED",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When member arrived at venue",
                        null=True,
                        verbose_name="checked in at",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When visit was completed",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="cancellation reason"),
                ),
                (
                    "check_in_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes from venue staff",
                        verbose_name="check-in notes",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cancelled by",
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who processed check-in",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="checked in by",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Which subscription plan was used for this booking",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="subscriptions.subscription",
                        verbose_name="subscription used",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "SUBSCRIBER"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="member",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        limit_choices_to={"status": "APPROVED"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="venues.venue",
                        verbose_name="venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Booking Created"),
                            ("CHECKED_IN", "Checked In"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "Marked No Show"),
                            ("MODIFIED", "Details Modified"),
                        ],
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="bookings.booking",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking activity",
                "verbose_name_plural": "booking activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "status"], name="bookings_bo_user_id_69a5d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["venue", "visit_date", "status"],
                name="bookings_bo_venue_i_ab7227_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["subscription", "status"], name="bookings_bo_subscri_c2779b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_reference"], name="bookings_bo_booking_8a7545_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["-created_at"], name="bookings_bo_created_7d6386_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("guests_count__gte", 1), ("guests_count__lte", 20)),
                name="valid_guest_count",
            ),
        ),
    ]
