# Generated by Django 5.2.7 on 2026-04-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("subscriptions", "0005_subscription_venue_tier_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_source",
            field=models.CharField(
                choices=[("SUBSCRIPTION", "Subscription"), ("STORE", "Discount Store")],
                default="SUBSCRIPTION",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Which subscription plan was used for this booking",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="subscriptions.subscription",
                verbose_name="subscription used",
            ),
        ),
    ]
